apiVersion: v2
name: opennebula-csi
description: OpenNebula CSI Plugin Helm Chart
type: application
home: https://github.com/SparkAIUR/storage-provider-opennebula
sources:
  - https://github.com/SparkAIUR/storage-provider-opennebula
# https://github.com/helm/helm/issues/9298
version: 0.4.4
appVersion: "v0.4.4"
