# Default values for opennebula-csi.

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

oneApiEndpoint: "http://localhost:2633/RPC2"

credentials:
  existingSecret:
    name: ""
    key: "credentials"
  inlineAuth: ""

image:
  repository: "nudevco/opennebula-csi"
  tag: "v0.3.1"
  pullPolicy: "IfNotPresent"

imagePullSecrets: []
debugPort: null

driver:
  logLevel: 5
  defaultDatastores: []
  datastoreSelectionPolicy: "least-used"
  allowedDatastoreTypes:
    - "local"
    - "ceph"
    - "cephfs"
  extraArgs: []
  env: []

featureGates:
  compatibilityAwareSelection: true
  detachedDiskExpansion: false
  cephfsExpansion: false
  cephfsSnapshots: false
  cephfsClones: false
  cephfsSelfHealing: false
  topologyAccessibility: false

controller:
  replicaCount: 1
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraArgs: []
  extraEnv: []

node:
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations:
    - operator: "Exists"
  affinity: {}
  extraArgs: []
  extraEnv: []

metrics:
  enabled: true
  path: /metrics
  driver:
    enabled: true
    port: 9810
  controller:
    service:
      annotations: {}
      labels: {}
    serviceMonitor:
      enabled: false
      namespace: ""
      interval: 30s
      scrapeTimeout: 10s
      labels: {}
      annotations: {}
  node:
    service:
      annotations: {}
      labels: {}
    serviceMonitor:
      enabled: false
      namespace: ""
      interval: 30s
      scrapeTimeout: 10s
      labels: {}
      annotations: {}
  ports:
    provisioner: 8685
    attacher: 8686
    resizer: 8687
    registrar: 8688

preflight:
  enabled: false
  failReleaseOnError: true
  image:
    repository: ""
    tag: ""
  datastores: []
  nodeStageSecretRefs: []
  provisionerSecretRefs: []

snapshotter:
  enabled: true
  image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
  extraArgs: []

storageClasses: []
