# Default values for opennebula-csi.

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

oneApiEndpoint: "http://localhost:2633/RPC2"

credentials:
  existingSecret:
    name: ""
    key: "credentials"
  inlineAuth: ""

image:
  repository: "ghcr.io/sparkaiur/opennebula-csi"
  tag: "latest"
  pullPolicy: "IfNotPresent"

imagePullSecrets: []
debugPort: null

driver:
  logLevel: 5
  defaultDatastores: []
  datastoreSelectionPolicy: "least-used"
  allowedDatastoreTypes:
    - "local"
  extraArgs: []
  env: []

controller:
  replicaCount: 1
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraArgs: []
  extraEnv: []

node:
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations:
    - operator: "Exists"
  affinity: {}
  extraArgs: []
  extraEnv: []

storageClasses: []
