package driver

const (
	eventReasonDatastoreSelected            = "DatastoreSelected"
	eventReasonDatastoreFallback            = "DatastoreFallback"
	eventReasonDatastoreRejected            = "DatastoreRejected"
	eventReasonSnapshotCreated              = "SnapshotCreated"
	eventReasonSnapshotDeleted              = "SnapshotDeleted"
	eventReasonCloneCreated                 = "CloneCreated"
	eventReasonExpandDeferred               = "ExpandDeferred"
	eventReasonAttachValidated              = "AttachValidated"
	eventReasonHotplugTimeoutScaled         = "HotplugTimeoutScaled"
	eventReasonHotplugRecoveryPath          = "HotplugRecoveryPath"
	eventReasonHotplugNodeBusy              = "HotplugNodeBusy"
	eventReasonHotplugQueued                = "HotplugQueued"
	eventReasonHotplugQueueTimeout          = "HotplugQueueTimeout"
	eventReasonHotplugCooldown              = "HotplugCooldown"
	eventReasonDeviceDiscoverySlow          = "DeviceDiscoverySlow"
	eventReasonDeviceDiscoveryTimeout       = "DeviceDiscoveryTimeout"
	eventReasonDeviceCacheHit               = "DeviceCacheHit"
	eventReasonDeviceCacheMiss              = "DeviceCacheMiss"
	eventReasonDeviceByIDResolved           = "DeviceByIDResolved"
	eventReasonDetachGraceStarted           = "DetachGraceStarted"
	eventReasonDetachGraceReused            = "DetachGraceReused"
	eventReasonDetachGraceExpired           = "DetachGraceExpired"
	eventReasonDetachGraceCancelled         = "DetachGraceCancelled"
	eventReasonDetachGraceBypassed          = "DetachGraceBypassed"
	eventReasonLastNodePreferenceInjected   = "LastNodePreferenceInjected"
	eventReasonStuckAttachmentDetached      = "StuckAttachmentDetached"
	eventReasonStuckAttachmentRepublish     = "StuckAttachmentRepublishRequested"
	eventReasonLocalImmediateBindingWarning = "LocalImmediateBindingWarning"
	eventReasonPreflightFailed              = "PreflightFailed"
)
