package driver

const (
	eventReasonDatastoreSelected            = "DatastoreSelected"
	eventReasonDatastoreFallback            = "DatastoreFallback"
	eventReasonDatastoreRejected            = "DatastoreRejected"
	eventReasonSnapshotCreated              = "SnapshotCreated"
	eventReasonSnapshotDeleted              = "SnapshotDeleted"
	eventReasonCloneCreated                 = "CloneCreated"
	eventReasonExpandDeferred               = "ExpandDeferred"
	eventReasonAttachValidated              = "AttachValidated"
	eventReasonHotplugTimeoutScaled         = "HotplugTimeoutScaled"
	eventReasonHotplugRecoveryPath          = "HotplugRecoveryPath"
	eventReasonHotplugNodeBusy              = "HotplugNodeBusy"
	eventReasonHotplugQueued                = "HotplugQueued"
	eventReasonHotplugQueueTimeout          = "HotplugQueueTimeout"
	eventReasonHotplugQueueStale            = "HotplugQueueStale"
	eventReasonHotplugCooldown              = "HotplugCooldown"
	eventReasonDeviceDiscoverySlow          = "DeviceDiscoverySlow"
	eventReasonDeviceDiscoveryTimeout       = "DeviceDiscoveryTimeout"
	eventReasonDeviceCacheHit               = "DeviceCacheHit"
	eventReasonDeviceCacheMiss              = "DeviceCacheMiss"
	eventReasonDeviceByIDResolved           = "DeviceByIDResolved"
	eventReasonDetachGraceStarted           = "DetachGraceStarted"
	eventReasonDetachGraceReused            = "DetachGraceReused"
	eventReasonDetachGraceExpired           = "DetachGraceExpired"
	eventReasonDetachGraceCancelled         = "DetachGraceCancelled"
	eventReasonDetachGraceBypassed          = "DetachGraceBypassed"
	eventReasonSameNodeDetachRescued        = "SameNodeDetachRescued"
	eventReasonLastNodePreferenceInjected   = "LastNodePreferenceInjected"
	eventReasonMaintenanceModePrepared      = "MaintenanceModePrepared"
	eventReasonMaintenanceModeBlocked       = "MaintenanceModeBlocked"
	eventReasonMaintenanceModeReady         = "MaintenanceModeReady"
	eventReasonMaintenanceModeReleased      = "MaintenanceModeReleased"
	eventReasonStuckAttachmentDetached      = "StuckAttachmentDetached"
	eventReasonStuckAttachmentRepublish     = "StuckAttachmentRepublishRequested"
	eventReasonLocalImmediateBindingWarning = "LocalImmediateBindingWarning"
	eventReasonPreflightFailed              = "PreflightFailed"
	eventReasonLocalVolumeStaleMount        = "LocalVolumeStaleMountDetected"
	eventReasonLocalVolumeRecoveryAttempted = "LocalVolumeRecoveryAttempted"
	eventReasonLocalVolumeRecoverySucceeded = "LocalVolumeRecoverySucceeded"
	eventReasonLocalVolumeRecoveryFailed    = "LocalVolumeRecoveryFailed"
	eventReasonLocalDeviceMissingReported   = "LocalDeviceMissingReported"
	eventReasonLocalDeviceRecoveryAttempted = "LocalDeviceRecoveryAttempted"
	eventReasonLocalDeviceRecoverySucceeded = "LocalDeviceRecoverySucceeded"
	eventReasonLocalDeviceRecoveryFailed    = "LocalDeviceRecoveryFailed"
	eventReasonLocalDeviceRecoverySkipped   = "LocalDeviceRecoverySkipped"
)
