apiVersion: v1
entries:
  opennebula-csi:
  - apiVersion: v2
    appVersion: v0.2.2
    created: "2026-03-19T21:04:09.656816962Z"
    description: OpenNebula CSI Plugin Helm Chart
    digest: 5a9dacae030e6fa15c2b6dd4e8df17a39fbc1f876014ffbe2aa65a13fdebd291
    home: https://github.com/SparkAIUR/storage-provider-opennebula
    name: opennebula-csi
    sources:
    - https://github.com/SparkAIUR/storage-provider-opennebula
    type: application
    urls:
    - https://sparkaiur.github.io/storage-provider-opennebula/charts/opennebula-csi-0.2.2.tgz
    version: 0.2.2
generated: "2026-03-19T21:04:09.65622934Z"
