apiVersion: v1
entries:
  opennebula-csi:
  - apiVersion: v2
    appVersion: v0.3.0
    created: "2026-03-19T22:44:54.930965322Z"
    description: OpenNebula CSI Plugin Helm Chart
    digest: 5fba359c869d722611bcf1624578126dc1910028fb2f854a5fdd652421b8e545
    home: https://github.com/SparkAIUR/storage-provider-opennebula
    name: opennebula-csi
    sources:
    - https://github.com/SparkAIUR/storage-provider-opennebula
    type: application
    urls:
    - https://sparkaiur.github.io/storage-provider-opennebula/charts/opennebula-csi-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: v0.2.2
    created: "2026-03-19T22:44:54.930486492Z"
    description: OpenNebula CSI Plugin Helm Chart
    digest: 5a9dacae030e6fa15c2b6dd4e8df17a39fbc1f876014ffbe2aa65a13fdebd291
    home: https://github.com/SparkAIUR/storage-provider-opennebula
    name: opennebula-csi
    sources:
    - https://github.com/SparkAIUR/storage-provider-opennebula
    type: application
    urls:
    - https://sparkaiur.github.io/storage-provider-opennebula/charts/opennebula-csi-0.2.2.tgz
    version: 0.2.2
generated: "2026-03-19T22:44:54.929950765Z"
