oneApiEndpoint: "http://opennebula.example.internal:2633/RPC2"

credentials:
  existingSecret:
    name: opennebula-csi-auth
    key: credentials

driver:
  defaultDatastores:
    - "default"
  datastoreSelectionPolicy: "least-used"
  allowedDatastoreTypes:
    - "local"

storageClasses:
  - name: opennebula-default
    reclaimPolicy: Delete
    allowVolumeExpansion: false
    volumeBindingMode: Immediate
    mountOptions: []
    parameters:
      datastoreIDs: "default"
      datastoreSelectionPolicy: "least-used"
      fsType: "ext4"
