apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: demo-opennebula-snapshot
spec:
  volumeSnapshotClassName: opennebula-csi
  source:
    persistentVolumeClaimName: demo-opennebula-pvc
