{{- if and (not .Values.credentials.existingSecret.name) .Values.credentials.inlineAuth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opennebula-csi.authSecretName" . }}
  namespace: {{ include "opennebula-csi.namespace" . }}
type: Opaque
stringData:
  {{ include "opennebula-csi.authSecretKey" . }}: {{ .Values.credentials.inlineAuth | quote }}
{{- end }}
