---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ printf "%s-controller" (include "opennebula-csi.fullname" .) }}
  namespace: {{ include "opennebula-csi.namespace" . }}
spec:
  serviceName: {{ include "opennebula-csi.fullname" . | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "opennebula-csi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
  replicas: {{ .Values.controller.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: opennebula-csi
        {{- with .Values.controller.podAnnotations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "opennebula-csi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: controller
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: {{ include "opennebula-csi.controllerServiceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: opennebula-csi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debugPort }}
          ports:
            - containerPort: {{ .Values.debugPort }}
              name: debug
              protocol: TCP
          {{- end }}
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v={{ .Values.driver.logLevel }}"
            {{- with .Values.driver.extraArgs }}
{{ toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.controller.extraArgs }}
{{ toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
{{ include "opennebula-csi.driverCommonEnv" . | nindent 12 }}
            {{- with .Values.controller.extraEnv }}
{{ toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.controller.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--default-fstype=ext4"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.9.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=2m"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
        - name: liveness-probe
          imagePullPolicy: IfNotPresent
          image: registry.k8s.io/sig-storage/livenessprobe:v2.16.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=9808
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
      volumes:
        - name: csi-socket-dir
          emptyDir: {}
