{{- $inventory := (get .Values "inventoryController") | default dict -}}
{{- $inventoryEnabled := (get $inventory "enabled") | default false -}}
{{- if $inventoryEnabled }}
{{- $inventoryReplicaCount := (get $inventory "replicaCount") | default 1 -}}
{{- $inventoryLogLevel := (get $inventory "logLevel") | default 3 -}}
{{- $inventoryPodAnnotations := (get $inventory "podAnnotations") | default (dict) -}}
{{- $inventoryNodeSelector := (get $inventory "nodeSelector") | default (dict) -}}
{{- $inventoryAffinity := (get $inventory "affinity") | default (dict) -}}
{{- $inventoryTolerations := (get $inventory "tolerations") | default (list) -}}
{{- $inventoryExtraArgs := (get $inventory "extraArgs") | default (list) -}}
{{- $inventoryExtraEnv := (get $inventory "extraEnv") | default (list) -}}
{{ $inventoryResources := (get $inventory "resources") | default (dict) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-inventory" (include "opennebula-csi.fullname" .) }}
  namespace: {{ include "opennebula-csi.namespace" . }}
spec:
  replicas: {{ $inventoryReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "opennebula-csi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: inventory-controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: inventory-controller
        {{- with $inventoryPodAnnotations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "opennebula-csi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: inventory-controller
    spec:
      serviceAccountName: {{ include "opennebula-csi.inventoryServiceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $inventoryNodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $inventoryAffinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $inventoryTolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: inventory-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--mode=inventory-controller"
            - "--v={{ $inventoryLogLevel }}"
            - "--vmodule=leaderelection=0"
            {{- with $inventoryExtraArgs }}
{{ toYaml . | nindent 12 }}
            {{- end }}
          env:
{{ include "opennebula-csi.driverCommonEnv" . | nindent 12 }}
            {{- with $inventoryExtraEnv }}
{{ toYaml . | nindent 12 }}
            {{- end }}
          {{- with $inventoryResources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
