---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opennebula-csi.nodeServiceAccountName" . }}
  namespace: {{ include "opennebula-csi.namespace" . }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-node-registrar-role" (include "opennebula-csi.fullname" .) }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-node-registrar-binding" (include "opennebula-csi.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "opennebula-csi.nodeServiceAccountName" . }}
    namespace: {{ include "opennebula-csi.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-node-registrar-role" (include "opennebula-csi.fullname" .) }}
  apiGroup: rbac.authorization.k8s.io
